const navigationList = [
  {
    id: 1,
    url: "/dashboard",
    name: "Dashboard",
    rel: "nooepener",
    active: false,
  },
  {
    id: 2,
    url: "/monitoring/voltage",
    name: "Voltage",
    rel: "nooepener",
    active: false,
  },
  {
    id: 3,
    url: "/monitoring/current",
    name: "Current",
    rel: "nooepener",
    active: false,
  },
  {
    id: 4,
    url: "/monitoring/ground",
    name: "Ground",
    rel: "nooepener",
    active: false,
  },
  {
    id: 5,
    url: "/monitoring/frequency",
    name: "Frequency",
    rel: "nooepener",
    active: false,
  },
  {
    id: 6,
    url: "/monitoring/temperature",
    name: "Temperature",
    rel: "nooepener",
    active: false,
  },
  {
    id: 7,
    url: "/monitoring/energy",
    name: "Energy",
    rel: "nooepener",
    active: false,
  },
  {
    id: 8,
    url: "/monitoring/pf",
    name: "Power Factor",
    rel: "nooepener",
    active: false,
  },
  {
    id: 9,
    url: "/monitoring/thdv",
    name: "THDv",
    rel: "nooepener",
    active: false,
  },
  {
    id: 10,
    url: "/monitoring/thdi",
    name: "THDi",
    rel: "nooepener",
    active: false,
  },
  {
    id: 11,
    url: "/logger/alarm",
    name: "Alarm Log",
    rel: "nooepener",
    active: false,
  },
  {
    id: 12,
    url: "/logger/database",
    name: "Database Log",
    rel: "nooepener",
    active: false,
  },
  {
    id: 13,
    url: "/logger/sd-card",
    name: "SD Card Log",
    rel: "nooepener",
    active: false,
  },
];
